#!/usr/bin/env python3
"""
correlate_segments.py

Part 3 of Fusion Analysis (Manual Segmentation Variant).
1.  Loads "Segments" from JSON (generated by divide_sections.py).
2.  Loads "Visual Captions" from CaptionAnalysis (generated by previous pipeline).
3.  Loads User Comments (JSON Dir or DOCX).
4.  Pre-filters Comments (Top-K Relevance) using Sentence-Transformers (optional but recommended).
5.  Uses LLM to perform ALL-PAIRS correlation:
    - Every selected comment is checked against EVERY segment.
    - Two passes per segment: Visual and Transcript.
6.  Outputs JSON with full correlation matrix and DOCX report with stats.

Usage:
    python correlate_segments.py \
        --segments_root ../data/manual_segmentation \
        --comments_root ../../VideoAnalysis/data/comments/conventional \
        --captions_root ../../CaptionAnalysis/data/integrated_caption/frames_embodied_captions_integrated \
        --output_dir ../results/segment_correlations \
        --model llama3 \
        --top_k 200
"""

import os
import sys
import json
import re
import argparse
from typing import List, Dict, Any, Optional
import math

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
except ImportError:
    Document = None

# Add local scripts dir to path for utils import
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
try:
    from config import Config
    from utils.llm_utils import generate_response, stream_parser
except ImportError:
    print("[WARN] Could not import utils.llm_utils. Ensure you are running from FusionAnalysis/scripts/")
    Config = None
    def generate_response(*args): raise NotImplementedError("LLM utils not found")
    def stream_parser(x): return x

# -------------------- Data Loading --------------------

def load_json(path: str) -> Dict:
    if not os.path.exists(path): return {}
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[ERR] Failed to load {path}: {e}")
        return {}

def load_captions_map(video_id: str, captions_root: str) -> Dict[str, str]:
    vid_dir = os.path.join(captions_root, video_id)
    if not os.path.isdir(vid_dir):
        vid_dir = captions_root
        
    cand_path = os.path.join(vid_dir, f"{video_id}_captions_integrated.json")
    if not os.path.exists(cand_path):
        if os.path.exists(vid_dir):
            for f in os.listdir(vid_dir):
                if f.endswith('.json') and video_id in f:
                    cand_path = os.path.join(vid_dir, f)
                    break
    
    if not os.path.exists(cand_path):
        print(f"[WARN] No captions found for {video_id} at {cand_path}")
        return {}
        
    data = load_json(cand_path)
    frame_map = {}
    for item in data.get('frames', []):
        fid = item.get('frame_id')
        cap = item.get('caption')
        if fid and cap:
            frame_map[fid] = cap
    return frame_map

def parse_comments_docx(docx_path: str) -> Dict[str, List[Dict[str, str]]]:
    if not Document: return {}
    doc = Document(docx_path)
    from collections import defaultdict
    by_video = defaultdict(list)
    
    cur_vid = None
    buffer = []

    def get_vid(text):
        if "youtu" not in text: return None
        m = re.search(r"v=([A-Za-z0-9_-]{11,})", text)
        if m: return m.group(1)
        m = re.search(r"youtu\.be/([A-Za-z0-9_-]{11,})", text)
        if m: return m.group(1)
        return None

    def flush():
        nonlocal buffer
        if cur_vid and buffer:
            joined = " ".join(buffer).strip()
            if joined:
                by_video[cur_vid].append({'comment': joined})
        buffer = []

    for para in doc.paragraphs:
        t = para.text.strip()
        vid = get_vid(t)
        if vid:
            flush()
            cur_vid = vid
        elif t:
            buffer.append(t)
    flush()
    return dict(by_video)

def load_comments(comments_input: str, video_id: str, preloaded_docx: Optional[Dict] = None) -> List[Dict[str, str]]:
    if preloaded_docx:
        return preloaded_docx.get(video_id, [])
    
    if os.path.isdir(comments_input):
        cand = os.path.join(comments_input, f"{video_id}.json")
        path = None
        if os.path.exists(cand): path = cand
        else:
            for root, _, files in os.walk(comments_input):
                if f"{video_id}.json" in files:
                    path = os.path.join(root, f"{video_id}.json")
                    break
        
        comments = []
        if path:
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    content = f.read().strip()
                    if not content: return []
                    try:
                        data = json.loads(content)
                        if isinstance(data, list):
                            for c in data:
                                if isinstance(c, dict) and 'text' in c: comments.append({'comment': c['text']})
                                elif isinstance(c, str): comments.append({'comment': c})
                        elif isinstance(data, dict) and 'text' in data:
                             comments.append({'comment': data['text']})
                    except json.JSONDecodeError:
                        for line in content.split('\n'):
                            if not line.strip(): continue
                            try:
                                obj = json.loads(line)
                                if 'text' in obj: comments.append({'comment': obj['text']})
                            except: pass
            except Exception as e:
                print(f"[ERR] Error reading comments {path}: {e}")
        return comments
    return []

# -------------------- Helpers --------------------

def enrich_segments(segments: List[Dict], frame_map: Dict[str, str]):
    for seg in segments:
        frames = seg.get('frames', [])
        captions = []
        for i, f in enumerate(frames):
            base = os.path.splitext(f)[0]
            if base in frame_map:
                # Add Frame ID to help LLM distinguish
                captions.append(f"Frame {i+1}: {frame_map[base]}")
        seg['visual_summary'] = "\n".join(captions) if captions else "(No visual info)"

# -------------------- Pre-Filtering (Sentence Transformers) --------------------

def filter_comments_by_relevance(segments: List[Dict], comments: List[Dict], top_k: int = 200, model_name: str = "all-mpnet-base-v2") -> List[Dict]:
    """
    Selects Top-K comments based on maximum similarity to ANY segment.
    """
    if len(comments) <= top_k:
        return comments

    print(f"[INFO] Filtering {len(comments)} comments to Top-{top_k} using {model_name}...")
    
    try:
        from sentence_transformers import SentenceTransformer
        import numpy as np
    except ImportError:
        print("[WARN] sentence-transformers or numpy not installed. Skipping filter (using all comments).")
        return comments

    # 1. Prepare Texts
    # Segment Text = Visual + Transcript
    seg_texts = []
    for s in segments:
        vis = s.get('visual_summary', '')
        trans = s.get('transcript', '')
        seg_texts.append(f"{vis}\n{trans}".strip())
    
    comment_texts = [c['comment'] for c in comments]

    # 2. Embed
    print("    Embedding segments & comments...")
    model = SentenceTransformer(model_name)
    seg_embs = model.encode(seg_texts, convert_to_tensor=True)
    comm_embs = model.encode(comment_texts, convert_to_tensor=True)
    
    # 3. Compute Pars
    # We want max similarity for each comment against ALL segments.
    # Shape: [Num Comments, Num Segments]
    from sentence_transformers import util
    cosine_scores = util.cos_sim(comm_embs, seg_embs).cpu().numpy() # [C, S]
    
    # 4. Score = Max over S
    max_scores = np.max(cosine_scores, axis=1) # [C]
    
    # 5. Select Top K
    top_indices = np.argsort(-max_scores)[:top_k]
    
    selected = []
    for i in top_indices:
        selected.append(comments[i])
        
    print(f"    Selected {len(selected)} comments.")
    return selected

# -------------------- Correlation Logic (All Pairs) --------------------

def construct_visual_prompt(segment_text: str, comments_batch: List[str]) -> str:
    batch_json = json.dumps(comments_batch, indent=2)
    return f"""
    You are matching user comments to a 10-second VIDEO SEGMENT based on its visual content.
    
    VISUAL CONTEXT (Captions of frames sampled from this 10s segment):
    {segment_text}
    
    COMMENTS TO CHECK:
    {batch_json}
    
    TASK:
    For EACH comment, determine if it correlates to the visual actions or objects shown in this specific segment.
    
    DEFINITIONS:
    - Correlated (true/false): Is the comment referring to or engaging with the visual content shown in these frames?
    - Score (0-100): How related is the comment to the visual content? (High = direct reference, Low = unrelated).
    - Explanation: A brief reason for the correlated value and score.
    
    OUTPUT FORMAT (Strict JSON list, same order as input):
    [
      {{"comment": "...", "correlated": true, "score": 90, "explanation": "Directly comments on the [object] seen in Frame 2"}},
      {{"comment": "...", "correlated": false, "score": 10, "explanation": "Generic comment, not engaging with visual content"}}
    ]
    """

def construct_transcript_prompt(segment_text: str, comments_batch: List[str]) -> str:
    batch_json = json.dumps(comments_batch, indent=2)
    return f"""
    You are matching user comments to a 10-second VIDEO SEGMENT based on its audio/speech.
    
    TRANSCRIPT CONTEXT (Spoken audio from this 10s segment):
    {segment_text}
    
    COMMENTS TO CHECK:
    {batch_json}
    
    TASK:
    For EACH comment, determine if it correlates to the speech or topic discussed in this specific segment.
    
    DEFINITIONS:
    - Correlated (true/false): Is the comment referring to or engaging with the speech/audio content of this segment?
    - Score (0-100): How related is the comment to the spoken content? (High = discusses the topic/quote, Low = unrelated).
    - Explanation: A brief reason for the correlated value and score.
    
    OUTPUT FORMAT (Strict JSON list, same order as input):
    [
      {{"comment": "...", "correlated": true, "score": 85, "explanation": "Responds primarily to the speaker's point about [topic]"}},
      {{"comment": "...", "correlated": false, "score": 0, "explanation": "Unrelated to the speech text"}}
    ]
    """

def correlate_single_batch(prompt: str, model_name: str) -> List[Dict]:
    """
    Executes the LLM call with a pre-constructed prompt.
    """
    try:
        stream = generate_response(model_name, prompt)
        resp_text = "".join(stream_parser(stream)).strip()
        
        # Extract JSON
        m = re.search(r'\[.*\]', resp_text, flags=re.DOTALL)
        if m:
            try:
                results = json.loads(m.group(0))
                return results
            except json.JSONDecodeError:
                pass 
    except Exception as e:
        print(f"[ERR] Batch failed: {e}")
        
    return []

def run_all_pairs_correlation(segments: List[Dict], comments: List[Dict], model_name: str):
    """
    Iterates Segments -> Comments.
    Updates segments in-place with 'visual_correlations' and 'transcript_correlations'.
    """
    comment_texts = [c['comment'] for c in comments]
    batch_size = 5 # Small batch to ensure accuracy per segment
    
    for seg in segments:
        seg_idx = seg['segment_index']
        vis_text = seg.get('visual_summary', '').strip()
        trans_text = seg.get('transcript', '').strip()
        
        # init results containers
        seg['visual_correlations'] = []
        seg['transcript_correlations'] = []
        
        # --- Visual Pass ---
        if vis_text and vis_text != "(No visual info)":
            print(f"  [Seg {seg_idx}] Visual Check ({len(comment_texts)} comments)...")
            all_vis_results = []
            for i in range(0, len(comment_texts), batch_size):
                batch = comment_texts[i:i+batch_size]
                prompt = construct_visual_prompt(vis_text, batch)
                res = correlate_single_batch(prompt, model_name)
                all_vis_results.extend(res)
            seg['visual_correlations'] = all_vis_results
        
        # --- Transcript Pass ---
        if trans_text and trans_text != "(No speech)":
            print(f"  [Seg {seg_idx}] Transcript Check ({len(comment_texts)} comments)...")
            all_trans_results = []
            for i in range(0, len(comment_texts), batch_size):
                batch = comment_texts[i:i+batch_size]
                prompt = construct_transcript_prompt(trans_text, batch)
                res = correlate_single_batch(prompt, model_name)
                all_trans_results.extend(res)
            seg['transcript_correlations'] = all_trans_results

# -------------------- Reporting --------------------

def generate_docx_report(video_id: str, segments: List[Dict], total_comments: int, output_path: str):
    if not Document:
        print("[WARN] python-docx not installed. Skipping DOCX.")
        return

    doc = Document()
    doc.add_heading(f"Correlation Analysis: {video_id}", 0)
    
    # 1. Calc Stats
    num_segments = len(segments)
    checked_pairs_per_modality = num_segments * total_comments
    
    # Aggregators
    total_vis_correlated = 0
    total_trans_correlated = 0
    total_vis_high = 0 # score >= 60
    total_trans_high = 0
    
    # Union (At least one correlated)
    # This is tricky because we store lists. We assume order is preserved or we must match by comment string.
    # For now, let's just sum counts, as "Pairs".
    
    # "The number of segment comment pairs that has at least one correlated (visual or transcript)"
    # This implies we need to join by comment.
    
    count_union_correlated = 0
    count_union_high = 0
    
    for seg in segments:
        vis_list = seg.get('visual_correlations', [])
        trans_list = seg.get('transcript_correlations', [])
        
        # Map comment -> {vis_res, trans_res}
        # Assuming simple list order if perfectly aligned, but best to map by 'comment' text
        c_map = {}
        
        for r in vis_list:
            t = r.get('comment')
            if isinstance(t, list): 
                t = " ".join([str(x) for x in t])
            if not isinstance(t, str): 
                t = str(t)
                
            if t not in c_map: c_map[t] = {'v': None, 't': None}
            c_map[t]['v'] = r
            
        for r in trans_list:
            t = r.get('comment')
            if isinstance(t, list): 
                t = " ".join([str(x) for x in t])
            if not isinstance(t, str): 
                t = str(t)
                
            if t not in c_map: c_map[t] = {'v': None, 't': None}
            c_map[t]['t'] = r
            
        # Iterate unique comments for this segment
        for c_text, vals in c_map.items():
            v = vals['v']
            t = vals['t']
            
            is_v_corr = v and v.get('correlated')
            is_t_corr = t and t.get('correlated')
            
            v_score = v.get('score', 0) if v else 0
            t_score = t.get('score', 0) if t else 0
            
            if is_v_corr: total_vis_correlated += 1
            if is_t_corr: total_trans_correlated += 1
            if v_score >= 60: total_vis_high += 1
            if t_score >= 60: total_trans_high += 1
            
            if is_v_corr or is_t_corr:
                count_union_correlated += 1
                
            if v_score >= 60 or t_score >= 60:
                count_union_high += 1
    
    # 2. Write Summary
    doc.add_heading("Summary Statistics", 1)
    
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    
    def add_row(k, v):
        r = table.add_row().cells
        r[0].text = str(k)
        r[1].text = str(v)
        
    add_row("Total Segments", num_segments)
    add_row("Total Comments (Used)", total_comments)
    add_row("Total Checked Pairs (Per Modality)", checked_pairs_per_modality)
    add_row("", "")
    add_row("Correlated Pairs (Model Bool=True)", "")
    add_row("  - Visual", total_vis_correlated)
    add_row("  - Transcript", total_trans_correlated)
    add_row("  - Union (Vis OR Trans)", count_union_correlated)
    add_row("", "")
    add_row("High Score Pairs (Score >= 60)", "")
    add_row("  - Visual", total_vis_high)
    add_row("  - Transcript", total_trans_high)
    add_row("  - Union (Vis OR Trans)", count_union_high)
    
    doc.add_heading("Detailed Correlations", 1)
    doc.add_paragraph("Only pairs with Score >= 60 are listed below to conserve space.")
    
    for seg in segments:
        idx = seg['segment_index']
        doc.add_heading(f"Segment {idx} ({int(seg['start_time'])}-{int(seg['end_time'])}s)", 2)
        
        # Display Context
        p = doc.add_paragraph()
        p.add_run("Visual: ").bold = True
        vis_sum = seg.get('visual_summary', '')[:300] + "..." if len(seg.get('visual_summary', '')) > 300 else seg.get('visual_summary', '')
        p.add_run(vis_sum)
        
        p = doc.add_paragraph()
        p.add_run("Transcript: ").bold = True
        tr_sum = seg.get('transcript', '')[:300] + "..." if len(seg.get('transcript', '')) > 300 else seg.get('transcript', '')
        p.add_run(tr_sum)
        
        # List High Matches
        # Combine lists
        matches = []
        
        # Function to process lists
        def collect(src_list, type_lbl):
            for m in src_list:
                if m.get('score', 0) >= 60:
                    matches.append((m, type_lbl))
                    
        collect(seg.get('visual_correlations', []), "Visual")
        collect(seg.get('transcript_correlations', []), "Transcript")
        
        if matches:
            # Sort by score desc
            matches.sort(key=lambda x: x[0].get('score', 0), reverse=True)
            
            for m, mtype in matches:
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(f"[{mtype}] [{m.get('score')}] ").bold = True
                p.add_run(m.get('comment'))
                if m.get('explanation'):
                    p.add_run(f"\nWhy: {m.get('explanation')}").italic = True
        else:
            doc.add_paragraph("No high-confidence matches.")
            
        doc.add_paragraph("_" * 40)

    doc.save(output_path)


# -------------------- Main --------------------

def main():
    parser = argparse.ArgumentParser(description="Correlate Segments (All Pairs)")
    parser.add_argument("--segments_root", default="../data/segments_embodied", help="Folder with <vid>_manual_sections.json")
    # Updated default path from user request history or keep generic
    parser.add_argument("--comments_root", default="../../Data For Classes-Analysis/final_merged_data/final_merged_class_data.docx", help="Dir (JSON) or File (DOCX)")
    parser.add_argument("--captions_root", default="../../CaptionAnalysis/data/integrated_caption/frames_embodied_captions_integrated", help="Path to CaptionAnalysis")
    parser.add_argument("--output_dir", default="../results/segment_correlations_embodied", help="Path to output directory")
    parser.add_argument("--model", default="llama3")
    parser.add_argument("--top_k", type=int, default=200, help="Number of comments to keep (Top-K max similarity).")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    # Pre-load DOCX if needed
    preloaded = {}
    if args.comments_root.lower().endswith('.docx'):
        print(f"[INFO] Parsing Comments DOCX: {args.comments_root}")
        preloaded = parse_comments_docx(args.comments_root)
        
    # Find segment files
    if not os.path.exists(args.segments_root):
        print(f"[ERR] Segments root not found: {args.segments_root}")
        return
        
    seg_files = [f for f in os.listdir(args.segments_root) if f.endswith('_manual_sections.json')]
    print(f"[INFO] Found {len(seg_files)} segment files.")
    
    for f in seg_files:
        vid = f.replace('_manual_sections.json', '')
        
        # Resume Check
        out_json = os.path.join(args.output_dir, f"{vid}_segment_correlation.json")
        if os.path.exists(out_json):
            print(f"[SKIP] Results already exist for {vid}")
            continue

        print(f"\n=== Processing {vid} ===")
        
        # 1. Load Segments
        seg_path = os.path.join(args.segments_root, f)
        seg_data = load_json(seg_path)
        segments = seg_data.get('segments', [])
        if not segments:
            print("  No segments found.")
            continue
            
        # 2. Load Captions
        print("  Loading captions...")
        frame_map = load_captions_map(vid, args.captions_root)
        enrich_segments(segments, frame_map)
        
        # 3. Load Comments
        comments = load_comments(args.comments_root, vid, preloaded)
        print(f"  Found {len(comments)} raw comments.")
        
        if not comments:
            print("  Skipping (no comments).")
            continue
            
        # 4. Filter (Top-K)
        active_comments = filter_comments_by_relevance(segments, comments, top_k=args.top_k)
        
        # 5. All-Pairs Correlation
        print("  Running All-Pairs Correlation (Visual + Transcript)...")
        run_all_pairs_correlation(segments, active_comments, args.model)
        
        # 6. Save
        out_json = os.path.join(args.output_dir, f"{vid}_segment_correlation.json")
        result = {
            "video_id": vid,
            "duration": seg_data.get('duration', 0),
            "stats": {
                "total_comments": len(active_comments),
                "top_k_limit": args.top_k
            },
            "segments": segments
        }
        with open(out_json, 'w', encoding='utf-8') as f_out:
            json.dump(result, f_out, indent=2)
            
        out_docx = os.path.join(args.output_dir, f"{vid}_segment_correlation.docx")
        generate_docx_report(vid, segments, len(active_comments), out_docx)
        
        print(f"  > Saved to {args.output_dir}")

if __name__ == "__main__":
    main()
