#!/usr/bin/env python3
"""
correlate_segments.py

Part 3 of Fusion Analysis (Manual Segmentation Variant).
1.  Loads "Segments" from JSON (generated by divide_sections.py).
2.  Loads "Visual Captions" from CaptionAnalysis (generated by previous pipeline).
3.  Loads User Comments (JSON Dir or DOCX).
4.  Uses LLM to correlate comments to segments in TWO passes:
    - Pass 1: Visual Correlation (Comment vs Visual Summary)
    - Pass 2: Transcript Correlation (Comment vs Transcript)
5.  Outputs JSON with matched comments and DOCX report.

Usage:
    python correlate_segments.py \
        --segments_root ../data/manual_segmentation \
        --comments_root ../../VideoAnalysis/data/comments/conventional \
        --captions_root ../../CaptionAnalysis/data/integrated_caption/frames_embodied_captions_integrated \
        --output_dir ../results/segment_correlations \
        --model llama3
"""

import os
import sys
import json
import re
import argparse
from typing import List, Dict, Any, Optional

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
except ImportError:
    Document = None

# Add local scripts dir to path for utils import
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
try:
    from config import Config
    from utils.llm_utils import generate_response, stream_parser
except ImportError:
    # If standard Utils not found, create dummy for dry-run/testing if needed,
    # but based on context user has these.
    print("[WARN] Could not import utils.llm_utils. Ensure you are running from FusionAnalysis/scripts/")
    Config = None
    def generate_response(*args): raise NotImplementedError("LLM utils not found")
    def stream_parser(x): return x

# -------------------- Data Loading --------------------

def load_json(path: str) -> Dict:
    if not os.path.exists(path): return {}
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[ERR] Failed to load {path}: {e}")
        return {}

def load_captions_map(video_id: str, captions_root: str) -> Dict[str, str]:
    """
    Locates and loads the caption JSON for the video.
    Returns a dict: { "frame_XXXX": "caption text", ... }
    """
    # Structure seems to be: captions_root / <video_id> / <video_id>_captions_integrated.json
    # Or just flat? User showed: captions_integrated / frames_embodied_captions_integrated / <video_id> / <video_id>_captions_integrated.json
    
    vid_dir = os.path.join(captions_root, video_id)
    if not os.path.isdir(vid_dir):
        # Fallback: maybe just in root?
        vid_dir = captions_root
        
    # Search for json
    cand_path = os.path.join(vid_dir, f"{video_id}_captions_integrated.json")
    if not os.path.exists(cand_path):
        # Look for any json in vid_dir?
        if os.path.exists(vid_dir):
            for f in os.listdir(vid_dir):
                if f.endswith('.json') and video_id in f:
                    cand_path = os.path.join(vid_dir, f)
                    break
    
    if not os.path.exists(cand_path):
        print(f"[WARN] No captions found for {video_id} at {cand_path}")
        return {}
        
    data = load_json(cand_path)
    frame_map = {}
    for item in data.get('frames', []):
        fid = item.get('frame_id')
        cap = item.get('caption')
        if fid and cap:
            frame_map[fid] = cap
            
    return frame_map

def parse_comments_docx(docx_path: str) -> Dict[str, List[Dict[str, str]]]:
    """Parses DOCX comments (reused from correlate_sections)."""
    if not Document: return {}
    doc = Document(docx_path)
    by_video = {}
    from collections import defaultdict
    by_video = defaultdict(list)
    
    cur_vid = None
    buffer = []

    def get_vid(text):
        if "youtu" not in text: return None
        m = re.search(r"v=([A-Za-z0-9_-]{11})", text)
        if m: return m.group(1)
        m = re.search(r"youtu\.be/([A-Za-z0-9_-]{11})", text)
        if m: return m.group(1)
        return None

    def flush():
        nonlocal buffer
        if cur_vid and buffer:
            joined = " ".join(buffer).strip()
            if joined:
                by_video[cur_vid].append({'comment': joined})
        buffer = []

    for para in doc.paragraphs:
        t = para.text.strip()
        vid = get_vid(t)
        if vid:
            flush()
            cur_vid = vid
        elif t:
            buffer.append(t)
    flush()
    return dict(by_video)

def load_comments(comments_input: str, video_id: str, preloaded_docx: Optional[Dict] = None) -> List[Dict[str, str]]:
    """Loads comments for a video from JSON dir or preloaded DOCX."""
    if preloaded_docx:
        return preloaded_docx.get(video_id, [])
    
    if os.path.isdir(comments_input):
        cand = os.path.join(comments_input, f"{video_id}.json")
        path = None
        if os.path.exists(cand): path = cand
        else:
            for root, _, files in os.walk(comments_input):
                if f"{video_id}.json" in files:
                    path = os.path.join(root, f"{video_id}.json")
                    break
        
        comments = []
        if path:
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    content = f.read().strip()
                    if not content: return []
                    try:
                        data = json.loads(content)
                        if isinstance(data, list):
                            for c in data:
                                if isinstance(c, dict) and 'text' in c: comments.append({'comment': c['text']})
                                elif isinstance(c, str): comments.append({'comment': c})
                        elif isinstance(data, dict) and 'text' in data:
                             comments.append({'comment': data['text']})
                    except json.JSONDecodeError:
                        for line in content.split('\n'):
                            if not line.strip(): continue
                            try:
                                obj = json.loads(line)
                                if 'text' in obj: comments.append({'comment': obj['text']})
                            except: pass
            except Exception as e:
                print(f"[ERR] Error reading comments {path}: {e}")
        return comments
    return []

# -------------------- Helpers --------------------

def enrich_segments(segments: List[Dict], frame_map: Dict[str, str]):
    """
    Populate 'visual_summary' for each segment by aggregating captions of its frames.
    """
    for seg in segments:
        frames = seg.get('frames', [])
        captions = []
        for f in frames:
            # f might be "frame_0000.jpg" or "frame_0000.png"
            # caption map keys are "frame_0000"
            base = os.path.splitext(f)[0]
            if base in frame_map:
                captions.append(frame_map[base])
        
        # Simple concatenation or summary?
        # User asked for "correlation with comments".
        # Concatenating all frame captions might be too long for context window if specific frame-by-frame.
        # But usually we have ~3 frames per 10s segment. Concatenation is fine.
        seg['visual_summary'] = "\n".join(captions) if captions else "(No visual info)"

# -------------------- Correlation Logic --------------------

def run_llm_batch(context_key: str, context_label: str, segments: List[Dict], comments: List[str], model_name: str) -> List[Dict]:
    """
    Generic correlation function.
    context_key: key in segment dict to use as context (e.g., 'visual_summary' or 'transcript')
    context_label: label for prompt (e.g., "VISUAL DESCRIPTION" or "TRANSCRIPT")
    """
    
    # 1. Build Context String
    # To save tokens, we might only include non-empty contexts
    seg_context_str = ""
    valid_seg_ids = []
    
    for seg in segments:
        content = seg.get(context_key, "").strip()
        if not content or content == "(No visual info)" or content == "(No speech)":
            continue
            
        seg_context_str += f"Segment {seg['segment_index']}:\n{content}\n---\n"
        valid_seg_ids.append(seg['segment_index'])

    if not seg_context_str:
        return [] # No context to match against
    
    # 2. Prepare Batches
    batch_size = 5
    results = []
    
    for i in range(0, len(comments), batch_size):
        batch = comments[i:i+batch_size]
        
        prompt = f"""
        You are matching user comments to specific video segments based on {context_label}.
        
        VIDEO SEGMENTS:
        {seg_context_str}
        
        COMMENTS TO CLASSIFY:
        {json.dumps(batch, indent=2)}
        
        TASK:
        For each comment, determine if it correlates to any of the provided Segments based on the {context_label}.
        Return a correlation score (0-100) and a valid explanation.
        If multiple segments match, pick the strongest one. 
        If no segment matches well, return null or score 0.
        
        OUTPUT FORMAT (Strict JSON list):
        [
          {{"comment": "...", "segment_id": 1, "correlated": true, "score": 90, "explanation": "Refers to object described in visual"}},
          {{"comment": "...", "segment_id": null, "correlated": false, "score": 0, "explanation": "Generic comment"}}
        ]
        """
        
        try:
            stream = generate_response(model_name, prompt)
            resp_text = "".join(stream_parser(stream)).strip()
            
            # Extract JSON
            m = re.search(r'\[.*\]', resp_text, flags=re.DOTALL)
            if m:
                batch_results = json.loads(m.group(0))
                for res in batch_results:
                    if res.get('correlated') and res.get('segment_id') in valid_seg_ids:
                        results.append(res)
        except Exception as e:
            print(f"[ERR] Batch failed ({context_label}): {e}")
            
    return results

def dual_correlate(segments: List[Dict], comments: List[Dict], model_name: str):
    """
    Runs two passes of correlation.
    Mutates segments to add 'visual_matches' and 'transcript_matches'.
    """
    # Prepare unique comments text to avoid duplicate LLM calls if many dupes
    unique_texts = list({c['comment'] for c in comments})
    if len(unique_texts) > 100:
        print(f"[INFO] Sampling 100 comments out of {len(unique_texts)}.")
        unique_texts = unique_texts[:100]

    # PASS 1: Visual
    print("    Running Visual Correlation...")
    visual_results = run_llm_batch('visual_summary', 'VISUAL DESCRIPTION', segments, unique_texts, model_name)
    
    # PASS 2: Transcript
    print("    Running Transcript Correlation...")
    transcript_results = run_llm_batch('transcript', 'TRANSCRIPT content', segments, unique_texts, model_name)
    
    # Assign back to segments
    # Map results by segment_id
    for seg in segments:
        seg['visual_matches'] = []
        seg['transcript_matches'] = []
        
    for res in visual_results:
        sid = res.get('segment_id')
        if sid:
            # Find segment (assuming sorted index 1-N matches list index 0-(N-1))
            # Safest to search
            target = next((s for s in segments if s['segment_index'] == sid), None)
            if target:
                target['visual_matches'].append(res)
                
    for res in transcript_results:
        sid = res.get('segment_id')
        if sid:
            target = next((s for s in segments if s['segment_index'] == sid), None)
            if target:
                target['transcript_matches'].append(res)

# -------------------- Reporting --------------------

def generate_docx_report(video_id: str, segments: List[Dict], output_path: str):
    if not Document:
        print("[WARN] python-docx not installed. Skipping DOCX.")
        return

    doc = Document()
    doc.add_heading(f"Correlation Analysis: {video_id}", 0)
    
    # Summary Stats
    total_vis = sum(len(s['visual_matches']) for s in segments)
    total_trans = sum(len(s['transcript_matches']) for s in segments)
    
    doc.add_heading("Summary Statistics", 1)
    doc.add_paragraph(f"Total Segments: {len(segments)}")
    doc.add_paragraph(f"Total Visual Correlations: {total_vis}")
    doc.add_paragraph(f"Total Transcript Correlations: {total_trans}")
    
    doc.add_heading("Segment Details", 1)
    
    for seg in segments:
        vis_count = len(seg.get('visual_matches', []))
        trans_count = len(seg.get('transcript_matches', []))
        
        # Only show segments with matches? Or all? 
        # User said "Each section should have two correlation results".
        # Let's show all, but highlight active ones.
        
        h = doc.add_heading(f"Segment {seg['segment_index']} ({int(seg['start_time'])}-{int(seg['end_time'])}s)", 2)
        
        # Context Table
        table = doc.add_table(rows=1, cols=2)
        table.autofit = True
        hdr = table.rows[0].cells
        hdr[0].text = "Transcript Content"
        hdr[1].text = "Visual Summary"
        
        # Content Row
        row = table.add_row().cells
        row[0].text = seg.get('transcript', "").strip() or "(No speech)"
        vis_text = seg.get('visual_summary', "").strip()
        if len(vis_text) > 500: vis_text = vis_text[:500] + "..." # Truncate long captions in table
        row[1].text = vis_text or "(No visuals)"
        
        # Matches
        if vis_count > 0 or trans_count > 0:
            doc.add_heading("Matches", 3)
            
            if vis_count > 0:
                doc.add_paragraph(f"Visual Correlations ({vis_count}):", style='Heading 4')
                for m in seg['visual_matches']:
                    p = doc.add_paragraph(style='List Bullet')
                    p.add_run(f"[{m['score']}%] ").bold = True
                    p.add_run(f"{m['comment']}")
                    p.add_run(f"\nExample: {m['explanation']}").italic = True

            if trans_count > 0:
                doc.add_paragraph(f"Transcript Correlations ({trans_count}):", style='Heading 4')
                for m in seg['transcript_matches']:
                    p = doc.add_paragraph(style='List Bullet')
                    p.add_run(f"[{m['score']}%] ").bold = True
                    p.add_run(f"{m['comment']}")
                    p.add_run(f"\nReason: {m['explanation']}").italic = True
        else:
            doc.add_paragraph("No correlations found.", style='Body Text')
            
        doc.add_paragraph("_" * 40) # Divider

    try:
        doc.save(output_path)
    except Exception as e:
        print(f"[ERR] Failed to save DOCX: {e}")

# -------------------- Main --------------------

def main():
    parser = argparse.ArgumentParser(description="Correlate Segments (Dual Modality)")
    parser.add_argument("--segments_root", required=True, help="Folder with <vid>_manual_sections.json")
    parser.add_argument("--comments_root", required=True, help="Dir (JSON) or File (DOCX)")
    parser.add_argument("--captions_root", required=True, help="Path to CaptionAnalysis/.../integrated_caption")
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--model", default="llama3")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    # Pre-load DOCX if needed
    is_docx = False
    preloaded = {}
    if args.comments_root.lower().endswith('.docx'):
        print(f"[INFO] Parsing Comments DOCX: {args.comments_root}")
        preloaded = parse_comments_docx(args.comments_root)
        is_docx = True
        
    # Find segment files
    seg_files = [f for f in os.listdir(args.segments_root) if f.endswith('_manual_sections.json')]
    print(f"[INFO] Found {len(seg_files)} segment files.")
    
    for f in seg_files:
        # File name format: <vid>_manual_sections.json
        vid = f.replace('_manual_sections.json', '')
        print(f"\nProcessing {vid}...")
        
        # 1. Load Segments
        seg_path = os.path.join(args.segments_root, f)
        seg_data = load_json(seg_path)
        if not seg_data: continue
        segments = seg_data.get('segments', [])
        
        if not segments:
            print("  No segments found in file.")
            continue
            
        # 2. Load Captions
        print("  Loading captions...")
        frame_map = load_captions_map(vid, args.captions_root)
        enrich_segments(segments, frame_map)
        
        # 3. Load Comments
        comments = load_comments(args.comments_root, vid, preloaded)
        if not comments:
            print("  No comments found.")
            # We can still produce output with 0 matches if desired, or skip.
            # Let's proceed to show metadata at least.
        
        # 4. Correlate
        if comments:
            print(f"  Correlating {len(comments)} comments against {len(segments)} segments...")
            dual_correlate(segments, comments, args.model)
            
        # 5. Save Outputs
        out_json = os.path.join(args.output_dir, f"{vid}_segment_correlation.json")
        result = {
            "video_id": vid,
            "duration": seg_data.get('duration', 0),
            "segments": segments
        }
        with open(out_json, 'w', encoding='utf-8') as f_out:
            json.dump(result, f_out, indent=2)
            
        out_docx = os.path.join(args.output_dir, f"{vid}_segment_correlation.docx")
        generate_docx_report(vid, segments, out_docx)
        
        print(f"  > Saved to {args.output_dir}")

if __name__ == "__main__":
    main()
