#!/usr/bin/env python3
"""
correlate_sections.py

Part 2 of Fusion Analysis.
1.  Loads "Engagement Sections" from JSON (generated by generate_sections.py).
2.  Loads User Comments (JSON Dir or DOCX).
3.  Uses LLM to correlate comments to specific sections.
4.  Outputs JSON with matched comments.

Usage:
    python correlate_sections.py \
        --sections_root ../results/fusion_analysis/sections \
        --comments_root ../../VideoAnalysis/data/comments/conventional \
        --output_dir ../results/fusion_analysis/correlations \
        --model llama3
"""

import os
import sys
import json
import re
import argparse
from typing import List, Dict, Any, Optional

try:
    from docx import Document
except ImportError:
    Document = None

# Add local scripts dir to path for utils import
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
try:
    from config import Config
    from utils.llm_utils import generate_response, stream_parser
except ImportError:
    print("[WARN] Could not import utils.llm_utils. Ensure you are running from FusionAnalysis/scripts/")
    Config = None
    def generate_response(*args): raise NotImplementedError("LLM utils not found")
    def stream_parser(x): return x

# -------------------- Data Structures --------------------
# We need basic Dict structures, not strict classes for JSON loading simplicity

# -------------------- Data Loading --------------------

def load_sections(sections_path: str) -> Dict:
    """Load the sections JSON file for a video."""
    if not os.path.exists(sections_path):
        return {}
    try:
        with open(sections_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[ERR] Failed to load sections {sections_path}: {e}")
        return {}

def parse_comments_docx(docx_path: str) -> Dict[str, List[Dict[str, str]]]:
    """Parses DOCX comments."""
    if not Document:
        print("[WARN] python-docx not installed.")
        return {}
    doc = Document(docx_path)
    by_video = {}
    from collections import defaultdict
    by_video = defaultdict(list)
    
    cur_vid = None
    buffer = []

    def get_vid(text):
        if "youtu" not in text: return None
        m = re.search(r"v=([A-Za-z0-9_-]{11,})", text)
        if m: return m.group(1)
        m = re.search(r"youtu\.be/([A-Za-z0-9_-]{11,})", text)
        if m: return m.group(1)
        return None

    def flush():
        nonlocal buffer
        if cur_vid and buffer:
            joined = " ".join(buffer).strip()
            if joined:
                by_video[cur_vid].append({'comment': joined})
        buffer = []

    for para in doc.paragraphs:
        t = para.text.strip()
        vid = get_vid(t)
        if vid:
            flush()
            cur_vid = vid
        elif t:
            buffer.append(t)
    flush()
    return dict(by_video)

def load_comments(comments_input: str, video_id: str, preloaded_docx: Optional[Dict] = None) -> List[Dict[str, str]]:
    if preloaded_docx:
        return preloaded_docx.get(video_id, [])
    
    # Check Directory
    if os.path.isdir(comments_input):
        cand = os.path.join(comments_input, f"{video_id}.json")
        path = None
        if os.path.exists(cand): path = cand
        else:
            for root, _, files in os.walk(comments_input):
                if f"{video_id}.json" in files:
                    path = os.path.join(root, f"{video_id}.json")
                    break
        
        comments = []
        if path:
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    content = f.read().strip()
                    if not content: return []
                    try:
                        data = json.loads(content)
                        if isinstance(data, list):
                            for c in data:
                                if isinstance(c, dict) and 'text' in c: comments.append({'comment': c['text']})
                                elif isinstance(c, str): comments.append({'comment': c})
                        elif isinstance(data, dict) and 'text' in data:
                             comments.append({'comment': data['text']})
                    except json.JSONDecodeError:
                        for line in content.split('\n'):
                            if not line.strip(): continue
                            try:
                                obj = json.loads(line)
                                if 'text' in obj: comments.append({'comment': obj['text']})
                            except: pass
            except Exception as e:
                print(f"[ERR] Error reading comments {path}: {e}")
        return comments
    return []

# -------------------- Correlation Logic --------------------

def correlate_comments(sections: List[Dict], comments: List[Dict], model_name: str):
    """Correlate comments to sections using LLM."""
    profiles = ""
    for sec in sections:
        # Sections structure from JSON: {'id':..., 'title':..., 'summary':...}
        profiles += f"Section {sec.get('id')}: {sec.get('title')}\nSummary: {sec.get('summary')}\nVisuals: {sec.get('visual_cues')}\nKeywords: {sec.get('verbal_cues')}\n---\n"
        
    unique_comments = list({c['comment'] for c in comments})
    if len(unique_comments) > 100:
        print(f"[INFO] Sampling 100 comments out of {len(unique_comments)}.")
        unique_comments = unique_comments[:100]
        
    batch_size = 5
    for i in range(0, len(unique_comments), batch_size):
        batch = unique_comments[i:i+batch_size]
        
        prompt = f"""
        You are matching user comments to specific sections of a video.
        
        VIDEO SECTIONS:
        {profiles}
        
        COMMENTS TO CLASSIFY:
        {json.dumps(batch, indent=2)}
        
        TASK:
        For each comment, identify which Section ID (1, 2, 3...) it correlates to most strongly. 
        If it's generic or doesn't match specific content, use null.
        
        OUTPUT FORMAT (Strict JSON list of objects):
        [
          {{"comment": "...", "section_id": 1, "confidence": 90, "reason": "Mentions visual cue X"}},
          {{"comment": "...", "section_id": null, "confidence": 0, "reason": "Generic praise"}}
        ]
        """
        try:
            stream = generate_response(model_name, prompt)
            resp_text = "".join(stream_parser(stream)).strip()
            m = re.search(r'\[.*\]', resp_text, flags=re.DOTALL)
            if m:
                results = json.loads(m.group(0))
                for res in results:
                    sec_id = res.get('section_id')
                    if sec_id:
                        for sec in sections:
                            if sec.get('id') == sec_id:
                                if 'matched_comments' not in sec: sec['matched_comments'] = []
                                sec['matched_comments'].append(res)
                                break
        except Exception as e:
            print(f"[ERR] Batch failed: {e}")

# -------------------- Reporting Logic --------------------

def _add_thumbnails_row(doc, frame_paths, width_in=1.2):
    """Add a row of images to the document."""
    if not frame_paths: return
    table = doc.add_table(rows=1, cols=len(frame_paths))
    table.autofit = True
    for i, path in enumerate(frame_paths):
        cell = table.rows[0].cells[i]
        paragraph = cell.paragraphs[0]
        if os.path.exists(path):
            try:
                run = paragraph.add_run()
                run.add_picture(path, width=Inches(width_in))
            except Exception:
                paragraph.text = "[Img Error]"
        else:
            paragraph.text = "[Missing]"

def generate_docx_report(video_id: str, sections: List[Dict], comments: List[Dict], output_path: str, is_youtube: bool, min_score: int = 60):
    """
    Generates a DOCX report.
    - is_youtube=True: Use statistical summary style (Stats, Top-K per section).
    - is_youtube=False (Student): Use detailed coverage style (Per-comment breakdown).
    """
    if not Document:
        print("[WARN] python-docx not installed. Skipping DOCX generation.")
        return

    doc = Document()
    source_label = "YouTube" if is_youtube else "Student/Class"
    doc.add_heading(f"Correlation Report: {video_id} ({source_label})", 0)
    
    # Pre-calculate matches
    # Structure: section['matched_comments'] = [{'comment':..., 'section_id':..., 'confidence':..., 'reason':...}]
    
    total_comments = len(comments)
    total_correlated = 0
    high_conf_correlated = 0
    
    # We need to map comments back to sections for stats
    # But sections already contain 'matched_comments' list from the correlation step.
    
    for sec in sections:
        matches = sec.get('matched_comments', [])
        total_correlated += len(matches)
        for m in matches:
            if m.get('confidence', 0) >= min_score:
                high_conf_correlated += 1
                
    # Summary
    doc.add_heading("Summary", level=1)
    doc.add_paragraph(f"Total Comments: {total_comments}")
    doc.add_paragraph(f"Total Correlated: {total_correlated} ({(total_correlated/total_comments*100) if total_comments else 0:.1f}%)")
    doc.add_paragraph(f"High Confidence (>={min_score}): {high_conf_correlated} ({(high_conf_correlated/total_comments*100) if total_comments else 0:.1f}%)")
    
    # ---------------- Student Style: Per-Comment Coverage ----------------
    if not is_youtube:
        doc.add_heading("Comment Coverage Analysis", level=1)
        # Invert the mapping: Comment -> Section(s)
        # Since our logic assigned 1 section per comment (mostly), this is simple.
        # But let's show it anyway.
        
        # We need to find comments that were NOT matched too?
        # The 'matched_comments' in sections only have the ones that matched.
        
        matched_texts = set()
        comment_map = {} # text -> {section_id, conf, reason}
        
        for sec in sections:
            for m in sec.get('matched_comments', []):
                txt = m.get('comment')
                matched_texts.add(txt)
                if txt not in comment_map: comment_map[txt] = []
                comment_map[txt].append({
                    'sec_id': sec['id'],
                    'sec_title': sec['title'],
                    'conf': m.get('confidence', 0),
                    'reason': m.get('reason', '')
                })
                
        # List all comments
        # Sort by: Matched (High Conf) > Matched (Low Conf) > Unmatched
        sorted_comments = []
        for c in comments:
            txt = c['comment']
            matches = comment_map.get(txt, [])
            best_conf = max([x['conf'] for x in matches]) if matches else -1
            sorted_comments.append((best_conf, txt, matches))
            
        sorted_comments.sort(key=lambda x: x[0], reverse=True)
        
        for conf, txt, matches in sorted_comments:
            p = doc.add_paragraph()
            if matches:
                p.add_run("[Matched] ").bold = True
                p.add_run(f"(Conf {conf}): {txt}")
                for m in matches:
                    doc.add_paragraph(f"  -> Section {m['sec_id']} ({m['sec_title']}): {m['reason']}", style='List Bullet')
            else:
                p.add_run("[Unmatched] ").italic = True
                p.add_run(txt)
                
    # ---------------- Common: Per-Section Details ----------------
    doc.add_heading("Section Details", level=1)
    
    # Sort sections by # of high-confidence matches? Or just time?
    # Time is natural for "Sections".
    
    for sec in sections:
        matches = sec.get('matched_comments', [])
        # Filter high confidence
        valid_matches = [m for m in matches if m.get('confidence', 0) >= min_score]
        
        # Header
        title = f"Section {sec['id']}: {sec['title']}"
        doc.add_heading(title, level=2)
        doc.add_paragraph(f"Time: {sec.get('start_time')} - {sec.get('end_time')}")
        
        # Stats
        if is_youtube:
            doc.add_paragraph(f"Matches: {len(matches)} (High Conf: {len(valid_matches)})")
            
        doc.add_paragraph(f"Summary: {sec.get('summary')}")
        
        if valid_matches:
            doc.add_heading(f"Top Matches ({len(valid_matches)})", level=3)
            # Sort by confidence
            valid_matches.sort(key=lambda x: x.get('confidence', 0), reverse=True)
            
            # For YouTube, limit to Top 10 to check doc size
            limit = 10 if is_youtube else 9999
            
            for m in valid_matches[:limit]:
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(f"[Conf {m.get('confidence')}]: ").bold = True
                p.add_run(m.get('comment'))
                if m.get('reason'):
                     doc.add_paragraph(f"  Reason: {m.get('reason')}")
            
            if len(valid_matches) > limit:
                doc.add_paragraph(f"... and {len(valid_matches) - limit} more.")
        else:
            doc.add_paragraph("(No high confidence matches)")
            
    try:
        doc.save(output_path)
    except Exception as e:
        print(f"[ERR] Failed to save DOCX: {e}")

# -------------------- Main --------------------

def main():
    parser = argparse.ArgumentParser(description="Fusion Analysis - Step 2: Correlation")
    parser.add_argument("--sections_root", required=True, help="Directory containing <video_id>_sections.json")
    parser.add_argument("--comments_root", required=True, help="Dir (JSON) or File (DOCX)")
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--model", default="llama3")
    
    args = parser.parse_args()
    
    # Pre-parse DOCX
    preloaded = None
    is_docx_input = False
    if os.path.isfile(args.comments_root) and args.comments_root.lower().endswith('.docx'):
        print(f"[INFO] Parsing DOCX: {args.comments_root}")
        preloaded = parse_comments_docx(args.comments_root)
        is_docx_input = True
        
    # Ensure correlation folder exists
    # User asked for: FusionAnalysis/results/correlation
    # If args.output_dir is passed as ".../results/fusion_analysis/correlations", that's fine.
    # We'll just use args.output_dir.
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)
        
    # Scan sections_root for JSONs
    files = [f for f in os.listdir(args.sections_root) if f.endswith('_sections.json')]
    print(f"[INFO] Found {len(files)} section files to process.")
    
    try:
        from docx.shared import Inches
    except: pass

    for f in files:
        vid = f.replace('_sections.json', '')
        print(f"\nProcessing {vid}...")
        
        sec_path = os.path.join(args.sections_root, f)
        data = load_sections(sec_path)
        if not data: continue
        
        sections = data.get('sections', [])
        comments = load_comments(args.comments_root, vid, preloaded)
        
        if not comments:
            print("  No comments found.")
        else:
            print(f"  Correlating {len(comments)} comments...")
            correlate_comments(sections, comments, args.model)
            
        # Save JSON results
        out_json = os.path.join(args.output_dir, f"{vid}_correlation.json")
        result = {
            "video_id": vid,
            "duration": data.get('duration', 0),
            "sections": sections # now contains matched_comments
        }
        with open(out_json, 'w', encoding='utf-8') as f_out:
            json.dump(result, f_out, indent=2)
            
        # Save DOCX Report
        out_docx = os.path.join(args.output_dir, f"{vid}_correlation.docx")
        # is_youtube logic: If input was NOT DOCX, assume YouTube (folder of JSONs)
        is_youtube = not is_docx_input
        
        generate_docx_report(vid, sections, comments, out_docx, is_youtube)

        print(f"  > Saved JSON and DOCX to {args.output_dir}")

if __name__ == "__main__":
    main()
