#!/usr/bin/env python3
"""
Export mean/sem summary for YouTube metrics from JSON files.
Input: JSON files generated by distinct collection runs (Conventional, Embodied).
Output: CSV file with columns:
  Label, 
  PctCorrMean, PctCorrSEM, 
  EngMean, EngSEM, 
  TopTopicPctMean, TopTopicPctSEM, 
  TopTopicScoreMean, TopTopicScoreSEM
"""

import json
import csv
import math
import statistics
import argparse
import os

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def get_stats(data_list):
    if not data_list:
        return 0.0, 0.0
    data_list = [x for x in data_list if x is not None]
    if not data_list:
        return 0.0, 0.0
        
    m = statistics.mean(data_list)
    try:
        s = statistics.stdev(data_list) if len(data_list) > 1 else 0.0
    except statistics.StatisticsError:
        s = 0.0
    sem = s / math.sqrt(len(data_list))
    return m, sem

def get_summary(data_dict):
    label = data_dict.get("label", "Unknown")
    videos = data_dict.get("videos", [])
    
    pct_corr = []
    engagement = []
    top_topic_pct = []
    top_score = []
    
    for v in videos:
        pct_corr.append(v.get("pct_correlated", 0))
        engagement.append(v.get("engagement", 0))
        top_topic_pct.append(v.get("top_topic_pct", 0))
        top_score.append(v.get("top_topic_avg_score", 0))
        
    return {
        "label": label,
        "PctCorr": get_stats(pct_corr),
        "Engagement": get_stats(engagement),
        "TopTopicPct": get_stats(top_topic_pct),
        "TopTopicScore": get_stats(top_score)
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--conventional', required=True, help="Path to Conventional JSON")
    parser.add_argument('--embodied', required=True, help="Path to Embodied JSON")
    parser.add_argument('--output', required=True, help="Output CSV path")
    args = parser.parse_args()

    c_data = load_json(args.conventional)
    e_data = load_json(args.embodied)
    
    s1 = get_summary(c_data)
    s2 = get_summary(e_data)
    
    headers = [
        "Label",
        "PctCorrMean", "PctCorrSEM",
        "EngMean", "EngSEM",
        "TopTopicPctMean", "TopTopicPctSEM",
        "TopTopicScoreMean", "TopTopicScoreSEM"
    ]
    
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    
    with open(args.output, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(headers)
        
        for s in [s1, s2]:
            row = [
                s["label"],
                f"{s['PctCorr'][0]:.4f}", f"{s['PctCorr'][1]:.4f}",
                f"{s['Engagement'][0]:.4f}", f"{s['Engagement'][1]:.4f}",
                f"{s['TopTopicPct'][0]:.4f}", f"{s['TopTopicPct'][1]:.4f}",
                f"{s['TopTopicScore'][0]:.4f}", f"{s['TopTopicScore'][1]:.4f}"
            ]
            w.writerow(row)
            
    print(f"Exported summary to {args.output}")

if __name__ == "__main__":
    main()
